export const quotes = [
    "The only way to do great work is to love what you do. – Steve Jobs",
    "Innovation distinguishes between a leader and a follower. – Steve Jobs",
    "Your time is limited, don't waste it living someone else's life. – Steve Jobs",
    "Stay hungry, stay foolish. – Steve Jobs",
    "The future belongs to those who believe in the beauty of their dreams. – Eleanor Roosevelt",
    "It is during our darkest moments that we must focus to see the light. – Aristotle",
    "Whoever is happy will make others happy too. – Anne Frank",
    "Do not go where the path may lead, go instead where there is no path and leave a trail. – Ralph Waldo Emerson",
    "The only impossible journey is the one you never begin. – Tony Robbins",
    "Believe you can and you're halfway there. – Theodore Roosevelt",
    "The best way to predict the future is to create it. – Peter Drucker",
    "The secret of getting ahead is getting started. – Mark Twain",
    "Don't watch the clock; do what it does. Keep going. – Sam Levenson",
    "The only person you are destined to become is the person you decide to be. – Ralph Waldo Emerson",
    "We may encounter many defeats but we must not be defeated. – Maya Angelou",
    "Life is 10% what happens to you and 90% how you react to it. – Charles R. Swindoll",
    "If you want to lift yourself up, lift up someone else. – Booker T. Washington",
    "The greatest glory in living lies not in never falling, but in rising every time we fall. – Nelson Mandela",
    "The journey of a thousand miles begins with a single step. – Lao Tzu",
    "Success is not final, failure is not fatal: it is the courage to continue that counts. – Winston Churchill",
    "I have not failed. I've just found 10,000 ways that won't work. – Thomas A. Edison",
    "The only true wisdom is in knowing you know nothing. – Socrates",
    "What you get by achieving your goals is not as important as what you become by achieving your goals. – Zig Ziglar",
    "Strive not to be a success, but rather to be of value. – Albert Einstein",
    "The mind is everything. What you think you become. – Buddha",
    "An unexamined life is not worth living. – Socrates",
    "Eighty percent of success is showing up. – Woody Allen",
    "The best revenge is massive success. – Frank Sinatra",
    "Our greatest weakness lies in giving up. The most certain way to succeed is always to try just one more time. – Thomas A. Edison",
    "The only thing necessary for the triumph of evil is for good men to do nothing. – Edmund Burke",
    "It does not matter how slowly you go as long as you do not stop. – Confucius",
    "Your ares is a paintbrush. – Bob Ross",
    "Keep your eyes on the stars, and your feet on the ground. – Theodore Roosevelt",
    "The only true wisdom is in knowing you know nothing. – Socrates",
    "If you want to achieve greatness stop asking for permission. – Unknown",
    "Things work out best for those who make the best of how things work out. – John Wooden",
    "To live is the rarest thing in the world. Most people exist, that is all. – Oscar Wilde",
    "Don’t be afraid to give up the good to go for the great. – John D. Rockefeller",
    "I find that the harder I work, the more luck I seem to have. – Thomas Jefferson",
    "Success is walking from failure to failure with no loss of enthusiasm. – Winston Churchill",
    "The starting point of all achievement is desire. – Napoleon Hill",
    "If you can dream it, you can achieve it. – Zig Ziglar",
    "The only thing we have to fear is fear itself. – Franklin D. Roosevelt",
    "The whole secret of a successful life is to find out what is one's destiny, and then do it. – Henry Ford",
    "The best time to plant a tree was 20 years ago. The second best time is now. – Chinese Proverb",
    "You miss 100% of the shots you don't take. – Wayne Gretzky",
    "Whether you think you can or you think you can't, you're right. – Henry Ford",
    "I alone cannot change the world, but I can cast a stone across the water to create many ripples. – Mother Teresa",
    "Nothing is impossible, the word itself says 'I'm possible'! – Audrey Hepburn",
    "The question isn't who is going to let me; it's who is going to stop me. – Ayn Rand",
    "If you want to be a successful writer, write a lot. And read a lot. – Stephen King",
    "The difference between a successful person and others is not a lack of strength, not a lack of knowledge, but rather a lack of will. – Vince Lombardi",
    "The most difficult thing is the decision to act, the rest is merely tenacity. – Amelia Earhart",
    "The greatest wealth is to live content with little. – Plato",
    "We are what we repeatedly do. Excellence, then, is not an act, but a habit. – Aristotle",
    "If you want to make your dreams come true, the first thing you have to do is wake up. – J.M. Power",
    "The only place where success comes before work is in the dictionary. – Vidal Sassoon",
    "Do what you can, with what you have, where you are. – Theodore Roosevelt",
    "The best revenge is to live a good life. – George Herbert",
    "You can't use up creativity. The more you use, the more you have. – Maya Angelou",
    "Twenty years from now you will be more disappointed by the things that you didn’t do than by the ones you did do. – Mark Twain",
    "The future belongs to those who believe in the beauty of their dreams. – Eleanor Roosevelt",
    "Either you run the day, or the day runs you. – Jim Rohn",
    "The most certain way to succeed is always to try just one more time. – Thomas Edison",
    "The only way to do great work is to love what you do. – Steve Jobs",
    "The best way to predict the future is to create it. – Abraham Lincoln",
    "The only thing that stands between you and your dream is the will to try and the belief that it is actually possible. – Joel Brown",
    "The big secret in life is that there is no big secret. Whatever your goal, you can get there if you're willing to work. – Oprah Winfrey",
    "The future starts today, not tomorrow. – Pope John Paul II",
    "The most important thing is to enjoy your life—to be happy—it's all that matters. – Audrey Hepburn",
    "The only person you are destined to become is the person you decide to be. – Ralph Waldo Emerson",
    "You can never cross the ocean until you have the courage to lose sight of the shore. – Christopher Columbus",
    "The man who moves a mountain begins by carrying away small stones. – Confucius",
    "If you are not willing to risk the usual, you will have to settle for the ordinary. – Jim Rohn",
    "Don't be afraid to fail. It's not the end of the world, and in many ways, it's the first step toward learning something and getting better at it. – Jon Hamm",
    "The only limit to our realization of tomorrow will be our doubts of today. – Franklin D. Roosevelt",
    "The best and most beautiful things in the world cannot be seen or even touched - they must be felt with the heart. – Helen Keller",
    "It is never too late to be what you might have been. – George Eliot",
    "With a new day comes new strength and new thoughts. – Eleanor Roosevelt",
    "We can't help everyone, but everyone can help someone. – Ronald Reagan",
    "The only way to achieve the impossible is to believe it is possible. – Charles Kingsleigh",
    "Start where you are. Use what you have. Do what you can. – Arthur Ashe",
    "I would rather die of passion than of boredom. – Vincent van Gogh",
    "A person who never made a mistake never tried anything new. – Albert Einstein",
    "If you don't build your dream, someone else will hire you to help them build theirs. – Tony Gaskins",
    "It's not what you look at that matters, it's what you see. – Henry David Thoreau",
    "The only true wisdom is in knowing you know nothing. – Socrates",
    "The secret of change is to focus all of your energy not on fighting the old, but on building the new. – Socrates",
    "Success is the sum of small efforts, repeated day-in and day-out. – Robert Collier",
    "The only thing that can stop you is you. – Unknown",
    "The greater danger for most of us isn't that our aim is too high and we miss it, but that it is too low and we reach it. – Michelangelo",
    "The future belongs to those who prepare for it today. – Malcolm X",
    "Success is about creating value. – Unknown",
    "In order to succeed, we must first believe that we can. – Nikos Kazantzakis",
    "The only way to make sense out of change is to plunge into it, move with it, and join the dance. – Alan Watts",
    "Don't count the days, make the days count. – Muhammad Ali",
    "The purpose of our lives is to be happy. – Dalai Lama",
    "I think goals should never be easy, they should force you to work, even if they are uncomfortable at the time. – Michael Jordan",
    "The only true wisdom is in knowing you know nothing. – Socrates",
    "Try not to become a man of success, but rather try to become a man of value. – Albert Einstein",
    "If you can't fly then run, if you can't run then walk, if you can't walk then crawl, but whatever you do you have to keep moving forward. – Martin Luther King Jr.",
    "The only way to do great work is to love what you do. If you haven't found it yet, keep looking. Don't settle. – Steve Jobs",
    "The best way to cheer yourself up is to try to cheer somebody else up. – Mark Twain",
    "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle. – Christian D. Larson",
    "You are never too old to set another goal or to dream a new dream. – C.S. Lewis",
    "The only limit to our realization of tomorrow will be our doubts of today. – Franklin D. Roosevelt"
];